### PR TITLE
AVX2 selection

### PR DESCRIPTION
**Pull request by mlochbaum**

### CODE REVIEW

**Comment by dzaima** [comment]
extremely misleading (due to only measuring executed instruction counts) [perf diff](https://dzaima.github.io/paste/#0vVpLb9s4EL7nVxgujLbw2uZLpOSkvmx77KlA73o62lUkwVKAZIv975XkSLRSy@aQkgMYIWVzZjgczuMbPRTlaxLOytc8/DIvw5dy4xfFfHdXul4S/vKyQxAeVn6WJG5ehNt2cP//XRn8VT6@/WBbZEkczHD@MvsghLjP3SCI0/2WVA@s/KX59TbNyk/bKD4U5cp/jJPgc/NknbpP4d9Z8vlXzXzlJvE@3R7i/WN5H2VpuYrcpzh53X78Gv7j/nye/XDTYvY9S7OPFdGHTSP87qERtvrnZcFr9e9QfR53NeGHTTWoJ0X8n5zgbkS6Ee1GrBtZ3Yh3I9GN7G7kSMpIDiUXLNlgyQdLRlhywpIVlrywZIYlNyK5kZM9SW5EciNvLDaNdupPsBM@54K7zKlXBPWjWaPQL3PP9f/dH7LnNKjPPjtsP0QRqv4wm@@WaI3Yol3RTNHiOgFKPEYJdua7VbWCLqAs5YqGAFImQPiRgKW8gvnNCmIZbKuZ4iGZ32nt3BQPTmHb90i1GbwmIOZIcR/X9ELpUS@sT4Bc5NZ@e2qqgXAR98LIs4CHiKmysJw3wlL1Y691uyJriqErLAGVSgyalhJLvLYo@NSc8exflQAzJUAmcUW9oyBIV8hWsXzwel10BKqejhsSwBoSnNfp6RWOgij0uAjt6Gb7@TN2qK4gpnZIodEGc1OlE4hLV3X4miaDxovvoCk8II2jXXzG4H0sGLPDQOBLsuOLU6L5LTjEg77FI7r5y7kOZB/T5Z5EKRfr5Ss@D5njEduBJp0myoQHMMUV2AbfMEv3mFqW07j5wUt9/XqhCVML7bDB4IUQA5@lWAA82OXrShRVPFgJMBp5rvADYUMDLDG49/Agrnrf2UJ/H8BSsGXpDJ3BrRLM9wTgNiymL/85@PQFA0tl6wVCRYEc8KYxvZhS6Pvk0yvMOXWq5MizsaJr0GNNJikedXmoQSF4vORGk8CUWvszAgGrjavl2SRhnIycV5xLGIXv2X5kCUGAeRLn0MyKOzDsiK5tINrE1LK3Hj7F4PiUDZUKjvUAEt9Wu9QADlLlwabnwcArLAQ7DwtS7BwtsTITC2pYGj7aMUEvlnB01jqFd1W35YCBbTjS6WirrvFtm7eO3ObYoLu7g3bqyrAoi6WfPeX9R6veI7KULa/nPHBLScDN8zANumkUJ2V46KY1lR6leiI7aftqaeYX74h9eymnaaVpImXgNJWQ8cIvHA1QNT3bJJdWDLo37CrZprk84YqF9JgwQE8CigcluAAKjt0CmNwjt9EM37apvdTCsS24FShBO0Y4tpZ9WyM6Qj0JMJoIF7k1MNzmrtpNrNYHG3U2lyYvDugj1WisbuytQUdIaOmbnTMhTHnGtI1woRZcY9AXWLBl0lEd8m1XoShNR4xNXypABunPzYAbNGEn/r3hjQKWMAR9UweBAQAKL7XJ9OW8/jsdx3rTWVMbXNRig7ecoG3CcwXnbw#html) because why not

**Comment by mlochbaum** [comment]
Oh, I new gather was going to measure wrong but didn't realize having gather be the baseline means gather versus shuffle is basically never going to show a change. Darn.

**Comment by mlochbaum** [comment]
That's quite a large change from d7a06be considering that it literally just adds a block of comments!

**Comment by dzaima** [comment]
`d7a06befb5` includes all commits in the range (fdfeb67e8f,d7a06befb5], i.e. 534c92f38a746f5e5cdeb73598918e443b6da191

**Comment by mlochbaum** [comment]
Yeah, just noticed.

**Pull request merged**
