### PR TITLE
Some changes for Windows builds with llvm-mingw

### PR DESCRIPTION
**Pull request by actalley**
These changes allow a build to succeed on Windows using `llvm-mingw` with the below command line.  No `•SH`, `•FFI`, or repl support for now, and other things may be broken.  Files with Unix line endings can be run with `-f`.

```sh
clang.exe -std=gnu11 -Wall -Wno-unused-function -fms-extensions -ffp-contract=off -fno-math-errno -Wno-microsoft-anon-tag -Wno-bitwise-instead-of-logical -Wno-unknown-warning-option -DBYTECODE_DIR=bytecodeSubmodule -DSINGELI=0 -DFFI=0 -fvisibility=hidden -DCBQN_EXPORT -DNO_MMAP -O3 -o bqn.exe src/opt/single.c -lm -lpthread
```

### CODE REVIEW

**Comment by dzaima** [comment]
could you cherry-pick the commit onto master to avoid the merge (for no particular reason other than me not liking a double-merge)? or should I do it along with the changes I'll make

**Comment by actalley** [comment]
Something is definitely going on with matrix. My messages have not been going through for a while.  I didn't see both commits.  Sorry about that.  I'll try the cherry-pick

**Comment by dzaima** [comment]
(fwiw, instead of closing, you can force-push to an existing PR's branch & it'll update)

**Comment by actalley** [comment]
Will that work with a cherry-pick onto master?

**Comment by dzaima** [comment]
it should work with anything afaik

**Comment by actalley** [comment]
After the cherry-pick I'm not seeing how to update the PR

**Comment by actalley** [comment]
Then I misunderstood what needed to be done. I don't know how to fix this

**Comment by dzaima** [comment]
pushed directly to `develop` as you did make a correct commit

**Comment by dzaima** [comment]
pushed some trivial changes to `develop`

**Comment by actalley** [comment]
I think I see what I did wrong.  The next one will be cleaner

**Pull request closed without merging**
