### PR TITLE
Write down libffi 3.3 as a compilation requirement

### PR DESCRIPTION
**Pull request by miguelraz**
No reason not to make it explicit.

### CODE REVIEW

**Comment by dzaima** [comment]
A reason to not make it explicit would be because it might make people try to get that specific version for no reason; I'd imagine any 3.x should work (fwiw my system has 3.4, so 3.3 wouldn't even be representative of what it gets mainly tested on); really, if it doesn't work on some libffi version in circulation I'd rather make it work in CBQN, than require moving to a newer version

**Comment by miguelraz** [comment]
Then maybe this can be ammended for `libffi 3.3>=`? 
It was challenging to not have tagged releases or semantic versioning for dependencies to figure out how to compile this for all systems.

**Comment by dzaima** [comment]
I would assume even `libffi 3.x` would do - though I haven't tried 3.0, the changelog doesn't indicate there that should be anything since then that CBQN relies on; that'd match all libffi versions released this millenium thus far, and I find it hard to believe libffi would ever introduce breaking changes; nevertheless, if you think explicitly mentioning 3.x is useful, we could go with that

**Comment by mlochbaum** [comment]
I think it might make sense to have a detailed "dependencies" section or something like that for package maintainers, but listing any version number in the main section README like this definitely seems to me like it would cause more confusion than it resolves.

**Comment by dzaima** [comment]
Added [this](https://github.com/dzaima/CBQN/tree/99563a3391a2457327887398782d7b2d17042857#requirements) section (currently at the replxx branch, will move to master soon™ if things go well)

**Pull request closed without merging**
