### PR TITLE
Add target `make musl-static`

### PR DESCRIPTION
**Pull request by dancek**
Another thing I need for the BQN slack bot that I've just done manually until now: building a binary on a modern machine that works on any ancient cloud runtime. This assumes the same platform – I've only tested on x86-64 Linux.

### CODE REVIEW

**Comment by dzaima** [comment]
Somewhat annoying is the conflict of "static" in relation to a static library archive vs statically linked binary. As of recently, directly using `build/build` can build static library archives, but that hasn't been mapped to a `make` target because of the aforementioned conflict, which I haven't yet bothered to decide on.

And, while it makes sense to have a statically linked binary target, should it really be merged with a specific `CC`? I'd think using an unchanged `CC`, requiring a manual `CC=musl-gcc` make arg if you want the specific one, would make more sense.

(also, PRs should go to the `develop` branch, not `master`; `master` points to the latest versioned release)

**Comment by dancek** [comment]
> Somewhat annoying is the conflict of "static" in relation to a static library archive vs statically linked binary. As of recently, directly using `build/build` can build static library archives, but that hasn't been mapped to a `make` target because of the aforementioned conflict, which I haven't yet bothered to decide on.

That's true. Another annoying thing is that statically linked binaries may either be truly standalone or still have external dependencies. Eg. if you compile statically with gcc+glibc on a bleeding-edge OS, the binary still won't work in a typical cloud environment due to needing newer glibc symbols.

> And, while it makes sense to have a statically linked binary target, should it really be merged with a specific `CC`? I'd think using an unchanged `CC`, requiring a manual `CC=musl-gcc` make arg if you want the specific one, would make more sense. (or maybe having both generic static and musl static if musl static is that common of a use-case and it's always `musl-gcc`)

With the above rationale, yes, it does make sense if you want a truly standalone binary. I don't know of other reasons to want a statically-compiled executable – and I think this one is quite a common thing to want. Maybe the target should be called something like `standalone` or `portable` to better convey what it's meant for. What do you think?

(`CC` could also be `musl-clang` but it cannot build CBQN currently.)

**Comment by dancek** [comment]
I do see that this PR is probably way too opinionated. All I want is a simple way to get a portable executable that works, without the end-user having to understand that glibc does `dlopen()` internally and C++ ABIs are complicated and what not. I wouldn't be surprised if there's a better approach to achieve that than what this PR does.

**Comment by dzaima** [comment]
How about `make static-bin` for a general `make LDFLAGS=-static FFI=0`, and having a note in the readme to use `make static-bin CC=musl-gcc REPLXX=0` to get a more proper self-contained one (allowing the user to tweak it as desired)?

**Pull request merged**
